INSERT INTO `job` (`id`, `name`) VALUES
(1, 'Pekař/Kuchař'),
(2, 'Sociální pracovník\r\n'),
(3, 'Pracovník v soc. službách'),
(4, 'Pekařka/kuchařka'),
(5, 'Odborný konzultant'),
(6, 'Uklízečka'),
(7, 'Číšník'),
(8, 'Servírka'),
(9, 'Administrativní pracovník'),
(10, 'IT technik'),
(11, 'Odborný asistent'),
(12, 'Manažer vzdělávání'),
(13, 'Vedoucí tlumočnických služeb'),
(14, 'Pracovník v soc. službách - koord. Kr. poboček'),
(15, 'Pracovní konzultant'),
(16, 'Lektor'),
(17, 'Vedoucí administrativy'),
(18, 'Grafik'),
(19, 'Administrativa - grafik'),
(20, 'Přepisovatelka'),
(21, 'Provozní ředitelka'),
(22, 'PR pracovník'),
(23, 'Vedoucí pracovník'),
(24, 'Mzdová účetní'),
(25, 'Účetní'),
(26, 'Švadlena'),
(27, 'Zprávař'),
(28, 'Vedoucí pracovník PR'),
(29, 'Pracovník komunikace'),
(30, 'Pracovní asistent'),
(31, 'Personalista'),
(32, 'Metodik'),
(33, 'Vedoucí sociální pracovník'),
(34, 'Editor'),
(35, 'Vedoucí účetní'),
(36, 'Operátor tiché linky'),
(37, 'Vedoucí komunikace'),
(38, 'Sociálně rehabilitační konzultant'),
(39, 'Sociální konzultant'),
(40, 'Právní konzultant'),
(41, 'Tlumočník'),
(42, 'Provozní ředitel'),
(43, 'Finanční a projektový ředitel'),
(44, 'Tlumočník - asistent'),
(45, 'Kamera, střih'),
(46, 'Cukřář/ka'),
(47, 'Asistent/ka'),
(48, 'Cukřář/ka, vedoucí směny'),
(49, 'IT podpora'),
(50, 'Vedoucí Tiché linky'),
(51, 'Technický ředitel'),
(52, 'řidič'),
(53, 'Provozní'),
(54, 'Koordinátor Tichý jazyk'),
(55, 'Konzultant'),
(56, 'právník');