parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.6'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            datetime_immutable: EvidApp\Shared\Infrastructure\Doctrine\DateTimeType
            EvidApp\User\Domain\ValueObject\Email: EvidApp\User\Infrastructure\Doctrine\EmailType
            EvidApp\User\Domain\ValueObject\Auth\HashedPassword: EvidApp\User\Infrastructure\Doctrine\HashedPasswordType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            UserDomain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/user/domain'
                prefix: 'EvidApp\User\Domain'
                alias: UserDomain
            UserProjections:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/user/projections'
                prefix: 'EvidApp\User\Infrastructure'
                alias: UserProjections
