security:
  encoders:
    auto:
      algorithm: auto

  providers:
    users:
      id: 'EvidApp\User\Infrastructure\Auth\AuthProvider'


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    auth:
      pattern:  ^/v1/auth
      stateless: true
      anonymous: true

    signup:
      pattern:  ^/v1/signup
      stateless: true
      anonymous: true

    secured:
      pattern:  ^/v1
      provider: users
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/auth,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/signup,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/,        roles: IS_AUTHENTICATED_FULLY       }
