version: "3.1"

volumes:
    db-data:

services:
    psql:
      image: postgres:11-alpine
      container_name: evidapp-db
      working_dir: /var/www/html
      volumes:
        - db-data:/var/www/html
      environment:
        - PSQL_ROOT_PASSWORD=docker_root
        - PSQL_DATABASE=db
        - PSQL_USER=user
        - PSQL_PASSWORD=pw
      ports:
        - "9932:5432"

    psql-test:
      image: postgres:11-alpine
      container_name: evidapp-db-test
      working_dir: /var/www/html
      volumes:
        - db-data:/var/www/html
      environment:
        - PSQL_ROOT_PASSWORD=docker_root
        - PSQL_DATABASE=db_test
        - PSQL_USER=user_test
        - PSQL_PASSWORD=pw_test
      ports:
        - "9933:5432"

    webserver:
      image: nginx:alpine
      container_name: evidapp-webserver
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: evidapp
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        XDEBUG_CONFIG: "remote_host=${localIp}"