version: "3.4"

volumes:
    db-data:

services:
    psql:
      image: postgres:11-alpine
      container_name: evidapp-db
      working_dir: /var/www/html
      volumes:
        - db-data:/var/www/html
      environment:
        POSTGRES_DB: evidapp
        POSTGRES_USER: evuser
        POSTGRES_PASSWORD: pass

    php:
      build: .docker/php-fpm
      container_name: evidapp
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      depends_on:
        - psql
        - rmq

    webserver:
      image: nginx:alpine
      container_name: evidapp-webserver
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php

    workers:
      image: jorge07/alpine-php:7.4-dev
      container_name: evidapp-workers
      volumes:
        - .:/var/www/html
      environment:
        ELASTIC_HOST: "elasticsearch:9200"
      command: ['/var/www/html/bin/console', 'rabbitmq:multiple-consumer', 'events']
      
    rmq:
      image: rabbitmq:3-management
      container_name: evidapp-rmq
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
      container_name: evidapp-elastic
      environment:
        - "discovery.type=single-node"
