imports:
  - { resource: application/use_case.yml }

services:
  leos.security.user_provider:
    class: Leos\Infrastructure\SecurityBundle\Security\UserProvider\UserProvider
    autowire: true

  leos.event.jwt_created_listener:
    class: Leos\Infrastructure\SecurityBundle\EventListener\JWTCreatedListener
    autowire: true
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }